use rand::Rng;

/// Generate a random email alias.
pub(crate) fn generate_random_alias() -> String {
    let mut rng = rand::thread_rng();
    let adjectives = [
        "ashen", "bleak", "civic", "cold", "covert", "drift", "echo", "grim", "iron", "kilo",
        "latent", "mute", "neon", "noir", "null", "omni", "pale", "quiet", "shadow", "silent",
        "static", "steel", "thin", "vanta", "acid", "arc", "blight", "brine", "brume", "carbon",
        "choke", "cipher", "cryo", "delta", "dusk", "ember", "feral", "fract", "ghost", "hollow",
        "hush", "ice", "ivory", "jett", "knife", "lunar", "mire", "murk", "mylar", "nadir",
        "night", "obsid", "onyx", "oxide", "plague", "ravel", "razor", "rot", "sable", "scar",
        "shard", "slate", "smoke", "suture", "toxin", "ultra", "umbra", "void", "weld", "wire",
        "wraith", "zero",
    ];
    let nouns = [
        "agent",
        "asset",
        "citizen",
        "client",
        "custodian",
        "drifter",
        "emissary",
        "enrollee",
        "entity",
        "index",
        "inmate",
        "node",
        "observer",
        "operative",
        "proxy",
        "report",
        "sector",
        "signal",
        "subject",
        "witness",
        "archive",
        "backdoor",
        "barrier",
        "census",
        "cipher",
        "command",
        "district",
        "echo",
        "firmware",
        "grid",
        "handler",
        "ledger",
        "lock",
        "mesh",
        "mirror",
        "module",
        "nexus",
        "protocol",
        "relay",
        "rubble",
        "sector",
        "shard",
        "siren",
        "station",
        "terminal",
        "vector",
        "vault",
        "ward",
        "zone",
    ];

    format!(
        "{}{}{}",
        adjectives[rng.gen_range(0..adjectives.len())],
        nouns[rng.gen_range(0..nouns.len())],
        rng.gen_range(1000..9999)
    )
}

/// Generate a random name.
pub(crate) fn generate_random_name() -> String {
    let mut rng = rand::thread_rng();
    let first_names = [
        "Amina",
        "Chidi",
        "Emeka",
        "Ifunanya",
        "Ifeoma",
        "Kelechi",
        "Ngozi",
        "Obinna",
        "Chinwe",
        "Uche",
        "Zainab",
        "Tunde",
        "Bola",
        "Sade",
        "Ade",
        "Kunle",
        "Amaka",
        "Chiamaka",
        "Chukwuemeka",
        "Oluwaseun",
        "Olamide",
        "Folake",
        "Yetunde",
        "Efe",
        "Nneka",
        "Ugo",
        "Chinonso",
        "Opeyemi",
        "Tope",
        "Ayodele",
        "Zubairu",
        "Hadiza",
        "Akira",
        "Hana",
        "Hiro",
        "Kenji",
        "Mei",
        "Rin",
        "Sora",
        "Yuki",
        "Jin",
        "Minseo",
        "Hyun",
        "Jisoo",
        "Soojin",
        "Daichi",
        "Keiko",
        "Yuna",
        "Kaito",
        "Ren",
        "Hina",
        "Sakura",
        "Takumi",
        "Yuto",
        "Haruka",
        "Aoi",
        "Minho",
        "Jiyoon",
        "Seojun",
        "Eunji",
        "Seoyeon",
        "Joon",
        "Hyejin",
        "Sooyoung",
        "Wei",
        "Jun",
        "Hao",
        "Ying",
        "Lin",
        "Xiu",
        "Bo",
        "Fang",
    ];
    let last_names = [
        "Okafor",
        "Adebayo",
        "Okoye",
        "Olawale",
        "Nwosu",
        "Eze",
        "Ibrahim",
        "Yusuf",
        "Chukwu",
        "Adeyemi",
        "Onyeka",
        "Balogun",
        "Fashola",
        "Umeh",
        "Nnamdi",
        "Sani",
        "Okon",
        "Nwachukwu",
        "Ogunleye",
        "Abiola",
        "Ogunbiyi",
        "Okojie",
        "Ekwueme",
        "Oduro",
        "Uzor",
        "Okpara",
        "Afolabi",
        "Ojo",
        "Adigun",
        "Ibe",
        "Okereke",
        "Nduka",
        "Li",
        "Wang",
        "Zhang",
        "Chen",
        "Liu",
        "Yang",
        "Zhao",
        "Wu",
        "Tanaka",
        "Sato",
        "Suzuki",
        "Watanabe",
        "Takahashi",
        "Yamamoto",
        "Nakamura",
        "Ito",
        "Kobayashi",
        "Kato",
        "Yoshida",
        "Yamada",
        "Sasaki",
        "Mori",
        "Abe",
        "Saito",
        "Kim",
        "Lee",
        "Park",
        "Choi",
        "Jung",
        "Kang",
        "Yoon",
        "Lim",
        "Jeon",
        "Han",
        "Song",
        "Shin",
        "Kwon",
        "Hwang",
        "Jang",
        "Yoo",
    ];

    format!(
        "{} {}",
        first_names[rng.gen_range(0..first_names.len())],
        last_names[rng.gen_range(0..last_names.len())]
    )
}
